server:
  port: 8081

spring:
  application:  
    name: user-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  file:
    path: D:/work/logs